version: "3"
services:
    prestashop:
        image: prestashop/prestashop:8.1.3-fpm
        # build:
        #     dockerfile: config-files/prestashop/Dockerfile
        #     context: .
            # args:
            #     - user=${UID}
        # user: ${UID}:${UID}
        expose:
            - "9000"
        depends_on:
            - mysql
        volumes:
            - ./www/:/var/www/html/
            - ./config-files/php/php.ini:/usr/local/etc/php/php.ini
        # restart: always
        environment:
        # - DB_PASSWD=pass
        - DB_PASSWD=${DB_PASSWORD}
        # - DB_NAME=prestashop
        - DB_NAME=${DB_DATABASE}
        - PS_INSTALL_AUTO=1
        - DB_SERVER=mysql 
        - PS_DOMAIN=${APP_URL}

    mysql:
        image: mysql:8.2.0
        ports:
            - "${MYSQL_PORT:-3306}"
        volumes:
            - db_data:/var/lib/mysql
            - ./config-files/mysql/conf.d/:/etc/mysql/conf.d
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        # restart: always

    apache:
        image: "httpd:2.4.58-alpine"
        ports:
            # - "8002:80"
            - "${APP_PORT:-80}:80"
            - "443"
        depends_on:
            - prestashop
        volumes:
            - ./www/:/var/www/html/
            - ./logs/apache2/:/var/log/apache2/
            - ./config-files/apache2/httpd.conf:/usr/local/apache2/conf/httpd.conf
        # restart: always

    ftpd_server:
        build:
            context: .
            dockerfile: ./config-files/ftp/Dockerfile
        container_name: pure-ftpd
        ports:
            - "21:21"
            - "30000-30009:30000-30009"
        volumes:
            - "${PWD}/www:/home/ftp/"
            - "/home/ftp/docker"
            - "/home/ftp/db"
            - "/home/ftp/.git"
        environment:
            PUBLICHOST: "localhost"
            FTP_USER_NAME: ${FTP_USER}
            FTP_USER_PASS: ${FTP_PASSWORD}
            FTP_USER_HOME: /home/ftp
        restart: always


    # SOURCE : https://hub.docker.com/_/phpmyadmin
    # phpmyadmin:
    #     image: phpmyadmin/phpmyadmin
    #     restart: always
    #     networks:
    #         - prestashop
    #     # links:
    #     #   - mysql:mysql
    #     ports:
    #         - 8081:80
    #     depends_on:
    #         - mysql
    #     environment:
    #         - PMA_HOST=mysql
    #         - PMA_USER=root
    #         - PMA_PASSWORD=toor

# networks:
#     prestashop:

volumes:
    db_data:
